# Build version
build.version=2.0

# Accounts-related settings
accounts.message=Welcome to EazyBank accounts related ConfigServer GIT Quality APIs
accounts.contactDetails.name=John Doe - QA 006320202 webhook Developer
accounts.contactDetails.email=john@eazybank.com
accounts.onCallSupport[0]=  (453) 392-4829
accounts.onCallSupport[1]=(236) 203-0384
