

build.version=3
accounts.message=Welcome to EazyBank Cards related ConfigServer defualt APIs
accounts.contactDetails.name=John Doe - Developer
accounts.contactDetails.email=john@eazybank.com
accounts.onCallSupport[0]=  (453) 392-4829
accounts.onCallSupport[1]=(236) 203-0384