

build.version=2.0
accounts.message=Welcome to EazyBank Loans related ConfigServer GIT Default APIs
accounts.contactDetails.name=John Doe - WEBHOO00OK  Developerrrrrrrrrrrrrrrrr
accounts.contactDetails.email=john@eazybank.com
accounts.onCallSupport[0]=  (453) 392-4829
accounts.onCallSupport[1]=(236) 203-0384



###spring.datasource.url=jdbc:mysql://127.0.0.1:3307/loansdb
###spring.datasource.username=root
###spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
###spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
###spring.jpa.hibernate.ddl-auto=update
